# Alternative nixpacks configuration
# Rename this to nixpacks.toml if the primary one doesn't work

[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
  "cd backend && npm ci --include=dev"
]

[phases.build] 
cmds = [
  "cd backend && npx prisma generate",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start"
